@startuml
skinparam monochrome true
skinparam shadowing false
title Hình 6.16 — State Diagram: Trạng thái đơn công tác phí


[*] --> ChoXuLy : Nhân viên tạo đề xuất
ChoXuLy : status = "Chờ duyệt"

ChoXuLy --> DaDuyet : HR/Manager duyệt
ChoXuLy --> TuChoi : HR/Manager từ chối

DaDuyet : status = "Đã duyệt"
DaDuyet : Ghi approvedBy\n+ timestamp

TuChoi : status = "Từ chối"

DaDuyet --> [*]
TuChoi --> [*]

@enduml
