@startuml
skinparam monochrome true
skinparam shadowing false
title Hình 6.14 — State Diagram: Trạng thái hợp đồng lao động


[*] --> HieuLuc : Tạo hợp đồng mới
HieuLuc : status = "Hiệu lực"
HieuLuc : Dùng để tính lương\nvà các phúc lợi

HieuLuc --> HetHan : endDate đã qua
HieuLuc --> DaThanhLy : HR thanh lý sớm

HetHan : status = "Hết hạn"
HetHan : Cảnh báo trước 30 ngày

DaThanhLy : status = "Đã thanh lý"

HetHan --> HieuLuc : Gia hạn hợp đồng
HetHan --> [*]
DaThanhLy --> [*]

@enduml
